package:
  name: jupyter-vcdat
  version: jupyter_vcdat_2.3.5_2020.05.12.12.36.45

source:
  git_rev: master
  git_url: git://github.com/cdat/jupyter-vcdat.git

build:
  number: 0
  noarch: python

requirements:
  host:
    - jupyterlab
    - nodejs
    - pip
    - 'python>=3.7'
  run:
    - cdms2
    - ipywidgets
    - jupyterhub
    - jupyterlab
    - nb_conda
    - nb_conda_kernels
    - 'python>=3.7'
    - tqdm
    - vcs

about:
  home:  https://github.com/cdat/jupyter-vcdat