proxy:
  secretToken: "3ef396509d1aa54e09e12854e441b05dc2424c720809ce95ddf7b40a49572942"
singleuser:
  image:
    # Get the latest image tag at:
    # https://hub.docker.com/r/jupyter/datascience-notebook/tags/
    # Inspect the Dockerfile at:
    # https://github.com/jupyter/docker-stacks/tree/master/datascience-notebook/Dockerfile
    # tag: 177037d09156
    name: cdoutrix/vcdat
    tag: next
    # name: jupyter/datascience-notebook
    # use jupyterlab
    defaultUrl: "/lab"
  lifecycleHooks:
    postStart:
      exec:
        command: ["gitpuller", "https://github.com/cdat/Jupyter-notebooks", "master"]
  memory:
    limit: 1.5G
    guarantee: 1G
  profileList:
      - display_name: "stable"
        description: "The stable version of VCDAT"
        default: true
      - display_name: "latest"
        description: "The latest version of VCDAT (nightly)"
        kubespawner_override:
            image: cdoutrix/vcdat:next
            storage:
                type: none
      - display_name: "core"
        description: "The core image before installing VCDAT extension"
        kubespawner_override:
            image: cdoutrix/vcdat:labextensions


hub:
  extraConfig:
    jupyterlab: |
      c.Spawner.cmd = ['jupyter-labhub']

