FROM cdoutrix/vcdat:lab-extensions
# Get the setup image
ENV CDAT_ANONYMOUS_LOG false
# extension
# run with --build-args BRANCH=master
# e.g.: sudo docker build --build-arg BRANCH=latest -f kube/Dockerfile.extension .
RUN jupyter-labextension install jupyter-vcdat@$BRANCH
