FROM jupyter/minimal-notebook:83ed2c63671f
# Get the latest image tag at:
# https://hub.docker.com/r/jupyter/minimal-notebook/tags/
# Inspect the Dockerfile at:
# https://github.com/jupyter/docker-stacks/tree/master/minimal-notebook/Dockerfile

RUN conda install -y -c cdat/label/v81 -c conda-forge nodejs "python=3.7" vcs pip nb_conda nb_conda_kernels plumbum mesalib && conda clean -y --all && pip install lazy_import && pip install sidecar

