version: 2

aliases:
  - &setup_miniconda
    name: setup_miniconda
    command: |
      mkdir -p workspace
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda3.sh
      bash ./miniconda3.sh -b -p $WORKDIR/miniconda

  - &create_conda_env
    name: create_conda_env
    command: |
       export PATH=$WORKDIR/miniconda/bin:$PATH
       conda config --set always_yes yes --set changeps1 no
       conda update -q conda
       conda config --set anaconda_upload no

  - &setup_jupyter_vcdat
    name: setup_jupyter_vcdat
    command: |
       export PATH=$WORKDIR/miniconda/bin:$PATH
       export CDAT_ANONYMOUS_LOG=False
       export CDAT_SETUP_PATH=${HOME}
       git status
       ./install_script.sh -v
       conda install -n jupyter-vcdat -c cdat/label/v81 -c conda-forge testsrunner cdat_info
       git status

  - &run_jupyter_vcdat
    name: run_jupyter_vcdat
    command: |
       export PATH=$WORKDIR/miniconda/bin:$PATH
       export CDAT_ANONYMOUS_LOG=False
       export CDAT_SETUP_PATH=${HOME}
       source activate jupyter-vcdat
       echo "XXX XXX XXX"
       pwd
       ls
       jupyter lab --ip='127.0.0.1'
    background: true

  - &run_tests_with_chrome
    name: run_tests_with_chrome
    environment:
      BROWSER_TYPE: "chrome"
      BROWSER_DRIVER: "/usr/local/bin/chromedriver"
    command: |
       export PATH=$WORKDIR/miniconda/bin:$PATH
       export CDAT_ANONYMOUS_LOG=False
       export CDAT_SETUP_PATH=${HOME}
       source activate jupyter-vcdat
       #python run_tests.py -H -v 2 tests/test_locators.py
       python run_tests.py -H -v 2 tests/test_load_a_variable.py
       #python run_tests.py -H -v 2 tests/test_load_variables_popup_locators.py
       #python run_tests.py -H -v 2 tests/test_plot_locators.py
       RESULT=$?
       echo "*** $PY_VER test result: "${RESULT} 
       exit $RESULT

  - &run_tests_with_firefox
    name: run_tests_with_firefox
    environment:
      BROWSER_TYPE: "firefox"
      BROWSER_BINARY: "/usr/local/bin/firefox"
      BROWSER_DRIVER: "/usr/local/bin/geckodriver"
    command: |
       export PATH=$WORKDIR/miniconda/bin:$PATH
       export CDAT_ANONYMOUS_LOG=False
       export CDAT_SETUP_PATH=${HOME}
       source activate jupyter-vcdat
       pip install selenium
       pip install pyvirtualdisplay
       nosetests -s tests/test_load_a_variable.py
       #python run_tests.py -H -v 2 tests/test_locators.py
       #python run_tests.py -H -v 2 tests/test_load_a_variable.py
       #python run_tests.py -H -v 2 tests/test_load_variables_popup_locators.py
       #python run_tests.py -H -v 2 tests/test_plot_locators.py
       RESULT=$?
       echo "*** $PY_VER test result: "${RESULT} 
       exit $RESULT

  - &conda_upload
    name: conda_upload
    environment:
       CHANNELS: "-c cdat/label/nightly -c conda-forge -c cdat"
    command: |
       export PATH=${HOME}/project/$WORKDIR/miniconda/bin:$PATH
       conda install conda-build anaconda-client
       conda config --set anaconda_upload no
       export CONDA_BLD_PATH=`pwd`/conda_build
       git clone git://github.com/cdat/conda-recipes
       cd conda-recipes
       export PKG_NAME=jupyter-vcdat
       export USER=cdat
       export VERSION=2.0.0
       if [[ $CIRCLE_BRANCH == 'master' ]]; then
        export LABEL=nightly
       else
        export LABEL=${CIRCLE_BRANCH}
       fi
       ln -s ../recipe $PKG_NAME
       python ./prep_for_build.py -l $VERSION -b ${CIRCLE_BRANCH}
       conda build $PKG_NAME $CHANNELS --python=3.6
       anaconda -t $CONDA_UPLOAD_TOKEN upload -u $USER -l $LABEL $CONDA_BLD_PATH/noarch/$PKG_NAME-$VERSION.`date +%Y*`0.tar.bz2 --force

  - &run_coveralls
    name: run_coveralls
    command: |
       export PATH=$WORKDIR/miniconda/bin:$PATH
       source activate jupyter-vcdat
       coveralls
       source deactivate

  - &prep_conda_cache
    name: prep_conda_cache
    command: |
       mv $WORKDIR/miniconda miniconda

  - &get_conda_cache
    name: get_conda_cache
    command: |
       mkdir -p $WORKDIR
       mv miniconda $WORKDIR/
       export PATH=$WORKDIR/miniconda/bin:$PATH
       conda config --set always_yes yes --set changeps1 no
       conda update -y -q conda
       conda config --set anaconda_upload no

  - &install_and_start_vncserver
    name: install_and_start_vncserver
    command: |
        sudo apt-get install -y x11vnc
        x11vnc -forever -nopw -create
    background: true

jobs:
  linux_jupyter_vcdat_py3:
    docker:
      #- image: circleci/node:12.2.0-stretch
      - image: circleci/node:jessie-browsers
      #- image: circleci/python:3-stretch-node-browsers
      - image: selenium/standalone-firefox:latest
    environment:
      WORKDIR: "workspace/test_firefox"
      PY_VER: "py3"
    steps:
      - checkout
      - run: which firefox
      - run: which geckodriver
      - run: *install_and_start_vncserver
      - run: *setup_miniconda
      - run: *setup_jupyter_vcdat
      - run: *run_jupyter_vcdat
      - run: pwd
      - run: ls
      - run: *run_tests_with_firefox
      - store_artifacts:
          path: tests_html
          destination: tests_firefox_html
      - run: *run_tests_with_chrome
      - store_artifacts:
          path: tests_html
          destination: tests_chrome_html
      #- run: *conda_upload

workflows:
  version: 2
  jupyter_vcdat:
    jobs:
      - linux_jupyter_vcdat_py3




