version: 2

aliases:
  - &setup_jupyter_vcdat
    name: setup_jupyter_vcdat
    command: |
       source activate jupyter-vcdat
       ./install_script.sh -v
       echo "xxx doing a conda install"
       conda install -n jupyter-vcdat -c cdat/label/v82 -c cdat/label/nightly -c conda-forge vcs libnetcdf=4.6.2 testsrunner cdat_info
       conda list
       npm install
       jupyter lab build
       jupyter-labextension install .
       echo "XXX npm list"
       npm list
       git status

  - &run_jupyter_vcdat
    name: run_jupyter_vcdat
    command: |
       export CDAT_ANONYMOUS_LOG=False
       source activate jupyter-vcdat
       conda list
       jupyter lab --ip='127.0.0.1'
    background: true

  - &run_tests_with_chrome
    name: run_tests_with_chrome
    environment:
      BROWSER_TYPE: "chrome"
      BROWSER_DRIVER: "/usr/local/bin/chromedriver"
    command: |
       source activate jupyter-vcdat
       python run_tests.py -H -v 2 tests/test_locators.py
       python run_tests.py -H -v 2 tests/test_load_a_variable.py
       python run_tests.py -H -v 2 tests/test_load_variables_popup_locators.py
       python run_tests.py -H -v 2 tests/test_plot_locators.py
       python run_tests.py -H -v 2 tests/test_edit_axis_locators.py
       RESULT=$?
       echo "*** $PY_VER test result: ${RESULT}"
       exit $RESULT

  - &run_tests_with_firefox
    name: run_tests_with_firefox
    environment:
      BROWSER_TYPE: "firefox"
      BROWSER_BINARY: "/usr/local/bin/firefox"
      BROWSER_DRIVER: "/usr/local/bin/geckodriver"
    command: |
       source activate jupyter-vcdat
       python run_tests.py -H -v 2 tests/test_locators.py
       python run_tests.py -H -v 2 tests/test_load_a_variable.py
       python run_tests.py -H -v 2 tests/test_load_variables_popup_locators.py
       python run_tests.py -H -v 2 tests/test_plot_locators.py
       python run_tests.py -H -v 2 tests/test_edit_axis_locators.py
       RESULT=$?
       echo "*** $PY_VER test result: ${RESULT}"
       exit $RESULT

  - &conda_upload
    name: conda_upload
    environment:
       CHANNELS: "-c cdat/label/nightly -c conda-forge -c cdat"
    command: |
       conda install conda-build anaconda-client
       conda config --set anaconda_upload no
       export CONDA_BLD_PATH=`pwd`/conda_build
       git clone git://github.com/cdat/conda-recipes
       cd conda-recipes
       export PKG_NAME=jupyter-vcdat
       export USER=cdat
       export VERSION=2.1.0
       if [[ $CIRCLE_BRANCH == 'master' ]]; then
        export LABEL=nightly
       else
        exit 0
       fi
       ln -s ../recipe $PKG_NAME
       python ./prep_for_build.py -l $VERSION -b ${CIRCLE_BRANCH}
       conda build $PKG_NAME $CHANNELS --python=3.6
       anaconda -t $CONDA_UPLOAD_TOKEN upload -u $USER -l $LABEL $CONDA_BLD_PATH/noarch/$PKG_NAME-$VERSION.`date +%Y*`0.tar.bz2 --force

  - &npm_publish
    name: npm_publish
    command: |
      if [[ $CIRCLE_BRANCH != 'master' ]]; then
        exit 0
      fi
      export CDAT_ANONYMOUS_LOG=False
      npm install
      npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      npm publish --tag nightly

  - &docker_publish
    name: docker_publish
    command: |
      cd kube
      docker login --username downie4 $DOCKER_TOKEN
      docker build --no-cache --tag=cdat/vcdat:nightly .
      docker push cdat/vcdat:nightly

jobs:
  publish:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - run: *npm_publish
      - setup_remote_docker
      - run: *docker_publish
  
  linux_jupyter_vcdat:
    docker:
      - image: cdat/vcdat_circleci:nightly
    environment:
      WORKDIR: "/tmp/jp-vcdat"
    steps:
      - checkout
      - run: echo 'export PATH=$WORKDIR/miniconda/bin:$PATH' >> $BASH_ENV
      - run: *setup_jupyter_vcdat
      - run: *run_jupyter_vcdat
      - run: sleep 15
      - run: *run_tests_with_chrome
      - store_artifacts:
          path: tests_html
          destination: tests_chrome_html
      - run: *run_tests_with_firefox
      - store_artifacts:
          path: tests_html
          destination: tests_firefox_html
      - store_artifacts:
          path: jupyter-vcdat_logfile.txt
      - run: *conda_upload

workflows:
  version: 2
  jupyter_vcdat:
    jobs:
      #- linux_jupyter_vcdat
      - publish
